Traceback (most recent call last):
  File "paynt/paynt.py", line 4, in <module>
    paynt.cli.main()
  File "/mnt/d/src/PP/synthesis/paynt/paynt/cli.py", line 96, in main
    paynt()
  File "/home/fpmk/synthesis/env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/fpmk/synthesis/env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/fpmk/synthesis/env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fpmk/synthesis/env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/d/src/PP/synthesis/paynt/paynt/cli.py", line 90, in paynt
    synthesizer.run()
  File "/mnt/d/src/PP/synthesis/paynt/paynt/synthesizers/pomdp.py", line 273, in run
    self.strategy_expected()
  File "/mnt/d/src/PP/synthesis/paynt/paynt/synthesizers/pomdp.py", line 128, in strategy_expected
    mdp,spec,selection,choice_values,expected_visits,hole_scores = self.solve_mdp(family)
  File "/mnt/d/src/PP/synthesis/paynt/paynt/synthesizers/pomdp.py", line 76, in solve_mdp
    for hole,score in res.primary_scores.items():
AttributeError: 'NoneType' object has no attribute 'items'
